### ISSUE TITLE
Missing some light and buoy/beacon data?

### ISSUE THREAD

**Issue by PetersonGIS** [terranodo/tegola-openseamap#11]
What we have so far is on the left and what openseamark is displaying is on the right. The circled features appear to have shape and colour data but our data is missing shape and colour information. The area depicted is #17.09/47.665575/9.189395.

![missinginfo2](https://user-images.githubusercontent.com/5266205/36168735-4ec4f9a0-10b7-11e8-8887-f0861c844e6a.JPG)

**Comment by erictheise** [comment]
Fixed with 18caf0b2.

![beacon-buoy-11](https://user-images.githubusercontent.com/317680/36499827-4f7a6c04-16f7-11e8-96ae-c67c8cc78c9d.png)
