### ISSUE TITLE
seamark_bridge_points clearance missing

### ISSUE THREAD

**Issue by PetersonGIS** [terranodo/tegola-openseamap#13]
Data for clearance is missing in seamark_bridge_points. The clearance is needed to display as text on the symbol.
![clearance](https://user-images.githubusercontent.com/5266205/36173509-8385d6e6-10c6-11e8-8d32-2000797e3077.JPG)

**Comment by erictheise** [comment]
Hmmm. The import schema I found originally differs from the one at the [detailed bridges page](https://wiki.openstreetmap.org/wiki/Seamarks/Bridges). I'll revise and rerun.

**Comment by erictheise** [comment]
Plenty of clearance data when I import a Europe Geofabrik extract locally. They'll surface tomorrow in a new planet import as

* clearance_width
* clearance_height
* clearance_height_closed
* clearance_height_open

Note that in 99.999% of the cases the values are floats but I saw a few oddballs float past that contained 'm.' for meters or had longer strings.

**Comment by erictheise** [comment]
New planet import is in place.

**Comment by PetersonGIS** [comment]
nice!
![clearance height](https://user-images.githubusercontent.com/5266205/36215967-c862801c-116a-11e8-8a49-f3ce84d5e5db.JPG)
