### ISSUE TITLE
Add type field to osm_topmark

### ISSUE THREAD

**Issue by PetersonGIS** [terranodo/tegola-openseamap#4]

**Comment by erictheise** [comment]
I've added `type` to all the tables. That was standard in `tegola-osm` and, based on a suggestion from @PetersonGIS, it'll help us reduce the number of tables by clustering entities having identical fields.

But `daymark` and `seamark` are special cases and I'm rerunning the import with a different config.

**Comment by erictheise** [comment]
Closing this issue with 49ec994.
