### ISSUE TITLE
Config syntax for abbreviations

### ISSUE THREAD

**Issue by PetersonGIS** [terranodo/tegola-openseamap#8]
Labels for the lights require a color abbreviation. Currently, on my local set-up, these labels are styled like this:

`{multiple}{character}.{colourabbrev}.{period}s({category})`

where colourabbrev is 
WG (white_green)
R (red)
G (green)

We need to add colourabbrev to the config sql for the seamark_light_points table. This is what I've been using, and it works, but I am not sure it is the best way to do it. Especially since there is more than just these three colours:

`replace(replace(replace(colour,'white;green','WG'), 'red','R'), 'green','G') AS colourabbrev, `

Putting this here as an issue to get input from others on the best way to do this.

According to [taginfo](https://taginfo.openstreetmap.org/keys/seamark:light:colour#values) the most frequent colors are: red, green, white, yellow. But there are a total of 23 unique colors that could potentially be in the db. 

If this is too onerous to put in the config then there is the possibility that we deal with this in the style.json with expressions.

**Comment by erictheise** [comment]
Is it 23 or only 9? [seamark:light:colour](https://wiki.openstreetmap.org/wiki/Seamarks/Lights#Colours) just has the 9.

Is the `colourabbrev` always just the first letter?

Our planet data has these distinct values:

amber
blue
green
green;red
green;red;green
green;white
orange
red
red;green
red;white
red;white;red
violet
white
white;green
white;green;white;green
white;red
white;red;green
white;red;white
white;red;white;red
white;white;red
yellow
yellow;green

We should be able to abbreviate any number of each colour with a regexp but just to be clear, the longer ones above would be __WGWG__ and __WRWR__?

**Comment by PetersonGIS** [comment]
We'll need to abbreviate all the colors in your list, above. But they aren't just the first letter as I'm realizing. I'll be back to post a list and their abbreviations in a bit. For now...

"white;green;white;green" :
![wgwg](https://user-images.githubusercontent.com/5266205/36039430-b1042b8a-0d7f-11e8-8776-e74de44f82e0.JPG)

"amber" 
![amber](https://user-images.githubusercontent.com/5266205/36039638-549b54ee-0d80-11e8-8a03-4a8f89988ff6.JPG)

**Comment by PetersonGIS** [comment]
| colourabbrev      | colour                  | symbol color in the map |
|-------------------|-------------------------|-------------------------|
| Am                | amber                   | orange                  |
| Bu                | blue                    | blue                    |
| G                 | green                   | green                   |
| GR                | green;red               | magenta                 |
| GW                | green;white             | magenta                 |
| Or                | orange                  | orange                  |
| R                 | red                     | red                     |
| RG                | red;green               | magenta                 |
| RW                | red;white               | magenta                 |
| RWR               | red;white;red           | magenta                 |
| Vi                | violet                  | violet                  |
| "" (empty string) | white                   | yellow                  |
| WG                | white;green             | magenta                 |
| WGWG              | white;green;white;green | magenta                 |
| WR                | white;red               | magenta                 |
| WRG               | white;red;green         | magenta                 |
| WRW               | white;red;white         | magenta                 |
| WRWR              | white;red;white;red     | magenta                 |
| WWR               | white;white;red         | magenta                 |
| Y                 | yellow                  | yellow                  |
| YG                | yellow;green            | magenta                 |

**Comment by erictheise** [comment]
Magenta doesn't map to an abbreviation? I was going to proceed by just converting the color strings to their abbreviations, e.g.,

green -> G
white;red;green -> WRG

**Comment by erictheise** [comment]
Hmmm, there is no Magenta according to [INT-1](https://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_P#Light_Colours) even though it's in [seamark:light:colour](https://wiki.openstreetmap.org/wiki/Seamarks/Lights#Colours).

**Comment by PetersonGIS** [comment]
Apparently there is no magenta in the tags, correct. Magenta might be included in the list of seamark light colours because it is used as a default light color in the rendering.

**Comment by PetersonGIS** [comment]
These two lights are tagged colour = white;red.
They are labeled with the colour abbreviation WR.
But they are rendered with a magenta light.

![whitered](https://user-images.githubusercontent.com/5266205/36045680-c1e34986-0d93-11e8-985b-86ac97733a00.JPG)

**Comment by theonecalledtom** [comment]
Yeah - I suspect just a fallback if the specified color is missing or not understood. Presumably someone who's worked on OSM would know this. In the WR category this is a alternating color so it seems like it defaults to magenta rather than trying to display both.

According to this page: http://www.sailingissues.com/navcourse9.html magenta is used in standard charts. I haven't found a good description of rules for mapping light characteristic to color.

**Comment by theonecalledtom** [comment]
perhaps not understood OR not clearly displayable?

**Comment by theonecalledtom** [comment]
Next question: Does OSM attempt any colorization of lights?

**Comment by theonecalledtom** [comment]
The more I read the more magenta seems like the traditional display/paper map option and colorization is only used on modern chart plotters and only for simple lights.

**Comment by PetersonGIS** [comment]
Interesting. If we want to "chart new territory" here we could actually modify these icons so that they exactly match the colour descriptions.

**Comment by erictheise** [comment]
@PetersonGIS, my instinct is to convert the color strings to the representation we've been talking about and to put logic in the style so that if what's there is either a single uppercase (G) or uppercase+lowercase (Vi), render the colour. If it's an empty string, render yellow and pretend it's white (aargh), if it's uppercase+uppercase, render magenta.

**Comment by erictheise** [comment]
Stretch goal would be to venture into _mare incognitum_ and investigate the creation and acceptance of new icons.

**Comment by PetersonGIS** [comment]
Agreed.

**Comment by theonecalledtom** [comment]
@erictheise  Perhaps I misunderstand but as a sailor I'd be inclined not to pretend anything. Better to default back to default and force the user to use their brains / read the string. These lights are critical safety information. White is an often used color. Magenta is not used (afaik). Better to fallback to not seen on the water than confuse users on the water with lights that are seen.

**Comment by erictheise** [comment]
@theonecalledtom, look either at the _"" (empty string)_ line in @PetersonGIS's table above or the  [seamark:light:colour](https://wiki.openstreetmap.org/wiki/Seamarks/Lights#Colours) table we've been discussing. The colour is _white_. It's rendered _yellow_. I find this confusing and I'm sorry if my facetious comment made it worse.

**Comment by theonecalledtom** [comment]
Might be historical. White light being some color temperature.

Here's another data source with a fairly clear colour mapping table (see page 78). 

https://msi.nga.mil/MSISiteContent/StaticFiles/NAV_PUBS/Chart1/ChartNo1_Updated.pdf

**Comment by erictheise** [comment]
Still need to capture the style side logic.

**Comment by PetersonGIS** [comment]
looking good.
![colourabbrev](https://user-images.githubusercontent.com/5266205/36216448-1788fbf2-116c-11e8-9822-3e2c4c3b610c.JPG)

**Comment by PetersonGIS** [comment]
(the "s" shouldn't be in these labels since there is no number before, but that's a separate issue.)
